site_name: Kubernetes the Hard way
repo_url: https://github.com/jizusun/kubernetes-the-hard-way
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
